export const PlaceActionTypes = {

    GET_PLACES_ITEMS:'GET_PLACES_ITEMS',
    GET_PLACES_START:'GET_PLACES_START',
    GET_PLACES_SUCCESS:'GET_PLACES_SUCCESS',
    GET_PLACES_FAIL:'GET_PLACES_FAIL',

};